name = "ai-dampness-assessment"
main = "src/worker.js"
compatibility_date = "2024-09-23"

# 靜態資源
[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ai-dampness-db"
database_id = "ee7ce644-7f94-42da-b21c-69da501a23f0"

[vars]
# NVIDIA_API_KEY (已透過 secret 設定)
# LINE_CHANNEL_ACCESS_TOKEN = ""
# LINE_CHANNEL_SECRET = ""
